### ISSUE TITLE
Simultaneous Tunnel Startup

### ISSUE THREAD

**Issue by Jonahss** [jmreidy/sauce-tunnel#18]
check out [this gist](https://gist.github.com/Jonahss/9396938)

Starting up two tunnels causes the second to immediately fail.

**Comment by apemberton** [comment]
Hi @Jonahss or others: does the latest version of Sauce Connect for osx (sc-4.3.11-osx) contain this fix? From what I see the pid file is still: /tmp/sauceconnect_client.pid on that version
