### ISSUE TITLE
The `tunnel.stop` callback is not called if there's a problem starting the tunnel.

### ISSUE THREAD

**Issue by jdalton** [jmreidy/sauce-tunnel#24]
I noticed that using Connect v4 on failed connections it will sit on `stop` never calling the `callback`. See [sauce-tunnel/index.js](https://github.com/jmreidy/sauce-tunnel/blob/4ae56e3cc73c8940dfc8657c6e1304b0b090b799/index.js#L126-L129).

I'm guessing this happens because when `tunnel.start(...)` passes a status of `false` to its callback the `proc` is already killed. So when I then call `tunnel.stop(...)` in the `start` callback for the `false` status it just waits forever.

**Comment by jmreidy** [comment]
Should be fixed with `2.2.2`. (I know this is an old bug and doesn't reflect that error you saw in 2.2.0 - but I think everything with stop should be working now.

**Comment by jdalton** [comment]
Thanks!
