### ISSUE TITLE
Verbose output

### ISSUE THREAD

**Issue by willchen90** [jmreidy/sauce-tunnel#42]
I've been using sauce-tunnel and it's been very helpful, however I can't seem to figure out how to print verbose output about the sauce tunnel (not just the sauce lab's selenium servers). The extraArgs array with the flag "--verbose" is for the selenium servers, but I want to see the line by line output from the Sauce Tunnel application. I'm not sure if I'm missing something, but I read through the READMe and still can't figure this out.

**Comment by woollybogger** [comment]
Each `SauceTunnel` instance is an `EventEmitter`, so you can listen to events that it emits with data, such as is done [here](https://github.com/jmreidy/sauce-tunnel/blob/master/test/sanity.js#L14-L19) in the test file. Is that the sort of thing you were looking for?

**Comment by woollybogger** [comment]
@willchen90 Did that answer your question?
