### ISSUE TITLE
Sauce Connect 4.3.10 is now available

### ISSUE THREAD

**Issue by Jonahss** [jmreidy/sauce-tunnel#44]
Hiyo :) New Sauce Connect version.

Download URLs/checksums:

https://saucelabs.com/downloads/sc-4.3.10-linux.tar.gz
SHA1: 744039a0f9530463eca62baf6d16cb9db8f836c7

https://saucelabs.com/downloads/sc-4.3.10-linux32.tar.gz
SHA1: 66d8e16b368dc65819f3a758de07234285ec6658

https://saucelabs.com/downloads/sc-4.3.10-osx.zip
SHA1: 6ec6f7e2af76a189ed8ceadd31282c5fce1e7dae

https://saucelabs.com/downloads/sc-4.3.10-win32.zip
SHA1: 0f29c39d062cb761a1c297b739301d7ef09bdd12

**Comment by jmreidy** [comment]
4.3.12 released on NPM as v2.3.0.
