### ISSUE TITLE
Please update to most recent version of Sauce Connect tunnel

### ISSUE THREAD

**Issue by andreas-marschke** [jmreidy/sauce-tunnel#49]
Current version supplied with this package (`4.3.9`) is not compatible anymore or it seems so as 
running the it results in this error on MacOSX:

```
Peer certificate cannot be authenticated with given CA certificates
```

Replacing the binary supplied in the vendor directory for `darwin` with the downloaded `sc` version (`4.3.12`) it works just fine.

This indicates a version compatibility issue.

Would you like to receive a PR for the most recent package versions?

**Comment by jmreidy** [comment]
Fixed with #50.
