### ISSUE TITLE
Sauce Connect 4.3.16 is out.

### ISSUE THREAD

**Issue by jdalton** [jmreidy/sauce-tunnel#54]
Just a heads up. When SauceLabs released Sauce Connect 4.3.15 somefolks noticed an issue causing intermittent crashes in the built-in HTTP proxy typically seen when a PAC is used and HTTPS websites are accessed. A new version (4.3.16) containing a fix for this is now available:

https://wiki.saucelabs.com/display/DOCS/Sauce+Connect

**Comment by jmreidy** [comment]
Thanks for the update. I'll get on this.

**Comment by jmreidy** [comment]
PS @jdalton I don't know what I'd do without your gentle reminders. 👍

**Comment by jdalton** [comment]
Closed by #55.
